Update sast.yml

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -29,7 +29,7 @@ jobs:
 
     - name: Run Semgrep
       id: semgrep
-      run: semgrep --config="p/php-laravel" --json > semgrep_results.json || echo "Semgrep failed"
+      run: semgrep --config= auto --json > semgrep_results.json || echo "Semgrep failed"
 
     - name: Check Semgrep Results File
       run: ls -la
